### ISSUE TITLE
TypeError: Cannot read property 'require' of undefined

### ISSUE THREAD

**Issue by shridhar-purandare** [mattlewis92/webpack-retry-chunk-load-plugin#48]
Hi,

We are using below dependencies:
"webpack": "5.64.2",
"webpack-bundle-analyzer": "3.8.0",
"webpack-cli": "4.5.0",
"webpack-dev-server": "3.11.2",
"webpack-manifest-plugin": "2.2.0",
"webpack-retry-chunk-load-plugin": "^3.1.1",

When we run the build we get following error in the build.

webpack/runtime/compat,webpack/runtime/compat,c,,,TypeError: Cannot read property 'require' of undefined
    at /home/vsts/work/1/s/node_modules/webpack-retry-chunk-load-plugin/dist/index.js:34:48
    at Hook.eval [as call] (eval at create (/home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at CompatRuntimeModule.generate (/home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/lib/runtime/CompatRuntimeModule.js:36:50)
    at CompatRuntimeModule.getGeneratedCode (/home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/lib/RuntimeModule.js:182:44)
    at CompatRuntimeModule.codeGeneration (/home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/lib/RuntimeModule.js:137:30)
    at /home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/lib/Compilation.js:3281:22
    at /home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Cache.get (/home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/home/vsts/work/1/s/node_modules/@mono/mono-scripts/node_modules/webpack/lib/CacheFacade.js:118:15)

It's coming at below line:
 ${webpack_1.RuntimeGlobals.getChunkScriptFilename} = function(chunkId){
              var result = oldGetScript(chunkId);
              return result + (queryMap.hasOwnProperty(chunkId) ? '?' + queryMap[chunkId]  : '');
            };

Can you please help @mattlewis92 ?

**Comment by sathishjobs** [comment]
i had same issue, i tried version 1.5, it is working fine. @shridhar-purandare

**Comment by ISyangk** [comment]
You should check whether the plug-in version corresponds to the webpack version

**Comment by mono-public** [comment]
For us, it was happening because we had another version of webpack in the dep tree. Once we fixed that, the error went away.

**Comment by shridhar-purandare** [comment]
For us, it was happening because we had another version of webpack in the dep tree. Once we fixed that, the error went away.
